# Generated by Django 3.1.7 on 2021-02-25 20:10

from django.db import migrations, models
import jmr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('key', models.CharField(default=jmr.models.generate_key, max_length=3, primary_key=True, serialize=False)),
                ('target', models.URLField(unique=True)),
            ],
        ),
    ]
